# netlify.toml
[build]
command = "npx prisma generate && prisma migrate deploy && npm run build"
publish = ".next"


[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "22"

# Set your environment variables in Netlify dashboard instead
